export const commands = {
  START: '/start',
  START_CRONS: '/start_crons',
  HELP: '/help',
  AUTHORIZE: '/authorize',
  ALL_CAMP_SCORE: '/all_camp_score',
  LYRICS: '/lyrics',
  ALL_CAMP_SCHEDULE: '/all_camp_schedule',
  INFO: '/info',
  // MY_SCHEDULE: '/my_schedule',
  MY_SCORE: '/my_score',
  MANAGE_MEETUPS: '/manage_meetups',
  SEND_MSG_FILE: '/send_msg_file',
  GET_ALL_SCORES: '/get_all_scores',
  ADD_POINTS: '/add_points',
  MANAGE_NOTIFY: '/manage_notify',
  // TODAY: '/today',
  // TOMORROW: '/tomorrow',
  // WHOLE: '/whole',
  GROUP1: '/group1',
  GROUP2: '/group2',
  GROUP3: '/group3',
  ORANGE: '/orange',
  PINK: '/pink',
  PURPLE: '/purple',
  NAVY: '/navy',
  WHITE: '/white',
  ALL_CAMP_AUDIENCE: '/all_camp_audience',
  ADD_MEETUP: '/add_meetup',
  EDIT_MEETUP: '/edit_meetup',
  DELETE_MEETUP: '/delete_meetup',
  ADD_NOTIFY: '/add_notify',
  EDIT_NOTIFY: '/edit_notify',
  DELETE_NOTIFY: '/delete_notify',
  DAY1: '/day1',
  DAY2: '/day2',
  DAY3: '/day3',
  DAY4: '/day4',
  DAY5: '/day5',
  DAY6: '/day6',
  EDIT_MEETUP_DAY: '/edit_meetup_day',
  EDIT_MEETUP_TITLE: '/edit_meetup_title',
  EDIT_MEETUP_TIME: '/edit_meetup_time',
  EDIT_MEETUP_FACILITATOR: '/edit_meetup_facilitator',
  EDIT_MEETUP_LINK: '/edit_meetup_link',
  EDIT_MEETUP_AUDIENCE: '/edit_meetup_audience',
  EDIT_NOTIFY_DAY: '/edit_notify_day',
  EDIT_NOTIFY_MSG: '/edit_notify_msg',
  EDIT_NOTIFY_TIME: '/edit_notify_time',
  EDIT_NOTIFY_AUDIENCE: '/edit_notify_audience',
}
