export const subCommands = {
  ADD_MEETUP_TITLE: '/add_meetup_title',
  ADD_MEETUP_TIME: '/add_meetup_time',
  ADD_MEETUP_FACILITATOR: '/add_meetup_facilitator',
  ADD_MEETUP_AUDIENCE: '/add_meetup_audience',
  ADD_MEETUP_LINK: '/add_meetup_link',
  ADD_MEETUP_CONFIRM: '/add_meetup_confirm',
  DELETE_MEETUP_CHOOSE_ONE: '/delete_meetup_choose_one',
  DELETE_MEETUP_CONFIRM: '/delete_meetup_confirm',
  EDIT_MEETUP_CHOOSE_ONE: '/edit_meetup_choose_one',
  EDIT_MEETUP_CHOOSE_PROP: '/edit_meetup_choose_prop',
  EDIT_MEETUP_TYPED_PROP: '/edit_meetup_typed_prop',
  EDIT_MEETUP_CONFIRM: '/edit_meetup_confirm',
  ADD_POINTS_TYPED_NUMBER: '/add_points_typed_number',
  ADD_POINTS_CHOOSE_ONE: '/add_points_choose_one',
  SEND_MSG_FILE_TYPE_MSG: '/send_msg_file_type_msg',
  SEND_MSG_FILE_ASK_FILE: '/send_msg_file_ask_file',
  SEND_MSG_FILE_LOAD_FILE: '/send_msg_file_load_file',
  SEND_MSG_FILE_CONFIRM_SENDING: '/send_msg_file_confirm_sending',
}
